//localhost:3000 tests
### Show all documents

GET http://localhost:3000/contacts

### Also show all document; redirect

GET http://localhost:3000/

### Show one contact by ID

GET http://localhost:3000/contacts/626c8981304b90ec6e07f986

### Create new contact

POST http://localhost:3000/contacts HTTP/1.1 
content-type: application/json

{
    "firstName": "Ringo",
    "lastName": "Starr",
    "email": "drummer@beatles.com",
    "favoriteColor": "purple",
    "birthday": "07/07/1940"
}

### Update a contact 

PUT http://localhost:3000/contacts/6279c53b396484761145293c HTTP/1.1
Content-Type: application/json

{
    "firstName": "You Replaced",
    "lastName": "Thiscontact",
    "email": "test@replace.com",
    "favoriteColor": "mauve",
    "birthday": "1/1/1912"
}

### Delete a contact

DELETE http://localhost:3000/contacts/6275d77e9833c8907e938639

//Heroku tests
###

GET https://still-lowlands-88073.herokuapp.com/contacts

### Redirect also work for GET contacts

GET https://still-lowlands-88073.herokuapp.com/

###

GET https://still-lowlands-88073.herokuapp.com/contacts/626c8981304b90ec6e07f986

###

POST https://still-lowlands-88073.herokuapp.com/contacts HTTP/1.1 
content-type: application/json

{
    "firstName": "Bruce",
    "lastName": "Springsteen",
    "email": "boss@estreet.com",
    "favoriteColor": "blue",
    "birthday": "09/23/1949"
}
### Update a contact 

PUT https://still-lowlands-88073.herokuapp.com/contacts/6275d6c319f24c568763c1e0 HTTP/1.1
Content-Type: application/json

{
    "firstName": "Replace 3rd",
    "lastName": "Contact",
    "email": "test@replace.com",
    "favoriteColor": "black",
    "birthday": "12/12/2012"
}

### Delete a contact

DELETE https://still-lowlands-88073.herokuapp.com/contacts/6276b770f70c03155389788f
